FileVersion = 1
Dependencies = {corlib = "*", raylib-beef = "*", prng-beef = "*"}

[Project]
Name = "ComprendRay"
StartupObject = "ComprendRay"

[Platform.Windows]
IconFile = "dist/icon_01.ico"

[Configs.Release.Win64]
StackSize = 4096
OptimizationLevel = "O2"
LTOType = "Thin"
VectorizeLoops = true
VectorizeSLP = true
