FileVersion = 1
Dependencies = {corlib = "*", raylib-beef = "*"}

[Project]
Name = "ComprendRay"
StartupObject = "ComprendRay"

[Configs.Release.Win64]
StackSize = 4096
OptimizationLevel = "O2"
LTOType = "Thin"
VectorizeLoops = true
VectorizeSLP = true
